# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ContentProvider_pb2 as ContentProvider__pb2


class SuzukiKasamiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestToken = channel.unary_unary(
                '/contentprovider.SuzukiKasamiService/RequestToken',
                request_serializer=ContentProvider__pb2.Request.SerializeToString,
                response_deserializer=ContentProvider__pb2.Ack.FromString,
                )
        self.ReceiveToken = channel.unary_unary(
                '/contentprovider.SuzukiKasamiService/ReceiveToken',
                request_serializer=ContentProvider__pb2.Token.SerializeToString,
                response_deserializer=ContentProvider__pb2.Ack.FromString,
                )


class SuzukiKasamiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuzukiKasamiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestToken,
                    request_deserializer=ContentProvider__pb2.Request.FromString,
                    response_serializer=ContentProvider__pb2.Ack.SerializeToString,
            ),
            'ReceiveToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveToken,
                    request_deserializer=ContentProvider__pb2.Token.FromString,
                    response_serializer=ContentProvider__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contentprovider.SuzukiKasamiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuzukiKasamiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/contentprovider.SuzukiKasamiService/RequestToken',
            ContentProvider__pb2.Request.SerializeToString,
            ContentProvider__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/contentprovider.SuzukiKasamiService/ReceiveToken',
            ContentProvider__pb2.Token.SerializeToString,
            ContentProvider__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
